# Generated by Django 4.2 on 2023-05-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('md', models.IntegerField(default=0)),
                ('td', models.IntegerField(default=0)),
                ('wd', models.IntegerField(default=0)),
                ('th', models.IntegerField(default=0)),
                ('fr', models.IntegerField(default=0)),
                ('st', models.IntegerField(default=0)),
                ('sd', models.IntegerField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.week')),
            ],
        ),
    ]
