# Generated by Django 4.2 on 2023-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='archived',
            field=models.BooleanField(default=0),
        ),
    ]
